"""migration

Revision ID: 5be30a4fbd0c
Revises: c26fa8ba1245
Create Date: 2023-12-09 13:23:07.254176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be30a4fbd0c'
down_revision = 'c26fa8ba1245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numerical_values',
    sa.Column('num', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numerical_values')
    # ### end Alembic commands ###
